
### Simple Debugging ###

Consider the example code used to compute the delay quantiles by month (see Delay Quantiles By 
Month ). We can use tryCatch for some simple debugging. See the error in line 7, there is no such v
ariable isdelayed

```{r eval=FALSE, tidy=FALSE}
map <- expression({
  tryCatch(
    {
      a <- do.call("rbind",map.values)
      a$delay.sec <- as.vector(a[,'arrive'])-as.vector(a[,'sarrive'])
      a <- a[!is.na(a$delay.sec),]
      a$isdelayed <- sapply(a$delay.sec,function(r) if(r>=900) TRUE else FALSE)
      a <- a[isdelayed==TRUE,] ## only look at delays greater than 15 minutes
      apply(a[,c('month','delay.sec')],1,function(r){
        k <- as.vector(unlist(r))
        if(!is.na(k[1])) rhcollect(k,1) # ignore cases where month is missing
      })
    },
    error = function(e) {
      e$message <- sprintf("Input File:%s\nAttempt ID:%s\nR INFO:%s",
        Sys.getenv("mapred.input.file"),
        Sys.getenv("mapred.task.id"),
        e$message
      )
      stop(e) ## WONT STOP OTHERWISE
    }
  )
})
reduce <- expression(
  pre = {
    sums <- 0
  } ,
  reduce = {
    sums <- sums + sum(unlist(reduce.values))
  },
  post = { 
    rhcollect(reduce.key, sums) 
  }
)
mapred <- list()
mapred$rhipe_map_buff_size <- 5
z <- rhwatch(
  map      = map,
  reduce   = reduce,
  combiner = TRUE,
  input    = rhfmt("/tmp/airline/output/blocks/", type = "sequence"),
  output   = rhfmt("/tmp/airline/output/quantiledelay", type = "sequence"),
  mapred   = mapred,
  readback = FALSE
)
```

Produces a slew of errors like (output slightly modified to fit page)

```
03/07/14 00:41:20 INFO mapred.JobClient: Task Id :
  attempt_201007281701_0273_m_000023_0, Status : FAILED
java.io.IOException: MROutput/MRErrThread failed:java.lang.RuntimeException:
R ERROR
=======
Error in `[.data.frame`(a, isdelayed == TRUE, ) : Input File:
Attempt ID:attempt_201007281701_0273_m_000023_0
R INFO:object "isdelayed" not found
```

It can be very useful to provide such debugging messages since R itself doesn’t provide much help. 
Use this to provide context about variables, such printing the first few rows of relevant data 
frames (if required). Moreover, some errors don’t come to the screen instead the job finishes 
successfully (but very quickly since the R code is failing) but the error message is returned as a 
counter. The splits succeed since Hadoop has finished sending its data to R and not listening to 
for errors from the R code. Hence any errors sent from R do not trigger a failure condition in 
Hadoop. This is a RHIPE design flaw. To compensate for this, the errors are stored in the counter 
`R_ERROR`.

Unfortunately, RHIPE does not offer much in the way of debugging. To run jobs locally that is, 
Hadoop will execute the job in a single thread on one computer, set `mapred.job.tracker` to local in 
the `mapred` argument of `rhwatch`. In this case, `shared` cannot be used and `copyFiles` will 
not work.

